FROM node:20-alpine AS builder

WORKDIR /app

# Копируем только существующие файлы, без хитростей с shell-операторами
COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.27-alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
